### ISSUE TITLE
Support android 6.0

### ISSUE THREAD

**Issue by binli** [mer-hybris/pulseaudio-modules-droid#54]
Hi,

Now I prepared to support android 6.0, I found there are droid-util-44.h, droid-util-44.h and droid-util-51.h headers file, and I compared these files, found a lot of different between each. So how do we generated the droid-util-xx.h files? I used a temp way to copy the droid-util-51.h to droid-util-60.h, it could be build successfully. What do I need to do to improve this header file for android 6.0? Thanks!

**Comment by jusa** [comment]
This is implemented now in 8.0.55 and onwards.
